# Site settings
title: Marvin Strangfeld
description: 'Open Source Developer'
url: 'http://strangfeld.io'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Marvin Strangfeld'
  email: marvin@strangfeld.io
  twitter_username: strangfeld_io
  github_username:  mstrangfeld
  linkedin_username:  marvin-strangfeld

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png', 'vendor', 'Makefile', 'LICENSE']
